# Generated by Django 6.1 on 2026-08-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(db_column='costo_unitario', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='estado',
            field=models.CharField(db_column='estado', default='disponible', max_length=50),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_column='fecha_vencimiento', null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='insumo_id',
            field=models.AutoField(db_column='insumo_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='insumo',
            name='nombre_insumo',
            field=models.CharField(db_column='nombre_insumo', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(db_column='stock_actual', default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(db_column='stock_minimo', default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(db_column='unidad_medida', default='Unidades', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, db_column='descripcion', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(db_column='nombre_producto', default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_id',
            field=models.AutoField(db_column='producto_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(db_column='precio', decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(db_column='cantidad', decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(db_column='insumo_id', on_delete=django.db.models.deletion.CASCADE, to='gestion.insumo')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
            options={
                'db_table': 'producto_insumo',
            },
        ),
    ]
